FROM node:latest
RUN mkdir app && cd app
COPY backend/package.json .
RUN npm install
COPY backend .

ENV AUTH=false
ENV URL=localhost:27017
ENV DB=admin
ENV SEED="huge pool glance daring own category scout dignity impulse field furnace pencil mistake spawn trac"

EXPOSE 3000
CMD [ "npm", "start" ]