FROM node:latest
RUN mkdir app && cd app
COPY backend/package.json .
RUN npm install
COPY backend .

ENV AUTH=true
ENV URL=35.204.142.46:27017
ENV LOGIN=root
ENV PASSWORD=
ENV DB=admin

ENV SEED="huge pool glance daring own category scout dignity impulse field furnace pencil mistake spawn trac"

EXPOSE 3000
CMD [ "npm", "start" ]